project:
  type: book
  preview:
    browser: true

book:
  title: "Reproducible Discrete-Event Simulation (DES) in Python and R"
  chapters:
  - index.qmd
  - pages/reproducibility.qmd
  - pages/des.qmd
  - part: "Methods"
    chapters:
    - pages/sampling.qmd
    - pages/software.qmd
    - pages/classes_functions.qmd
  search:
    location: navbar
    type: overlay
  navbar:
    collapse: false
    right:
      - icon: github
        href: https://github.com/pythonhealthdatascience/rap_des

format:
  html:
    theme: cosmo
    toc: true