name: simple-des
dependencies:
  - ipykernel=6.29.5
  - joblib=1.4.2
  - matplotlib=3.9.3
  - nbclient=0.10.1
  - nbformat=5.10.4
  - numpy=2.1.3
  - pandas=2.2.3
  - pyyaml=6.0.2
  - python=3.13.0
  - requests=2.32.3
  - scipy=1.14.1
  - simpy=4.1.1